<?php

/**
 * @file
 * Implements hooks and callbacks for this module.
 */
/**
 * Implements hook_permission().
 */
function islandora_westvault_permission() {
  return array(
    'ISLANDORA_WESTVAULT_SET_PRESERVATION' => array(
      'title' => t('Flag objects for preservation'),
      'description' => t('Select objects to be preserved.'),
      'restrict access' => TRUE,
    ),
    'ISLANDORA_WESTVAULT_ADMIN' => array(
      'title' => t('Administer Islandora Westvault'),
      'description' => t('Configure the Islandora Westvault module'),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Implements hook_menu().
 */
function islandora_westvault_menu() {
  $items['islandora/object/%islandora_object/manage/preservation'] = array(
    'title' => 'Preservation',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_westvault_form', 2),
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('ISLANDORA_WESTVAULT_SET_PRESERVATION'),
    'file' => 'includes/management_form.inc',
  );
  $items['admin/islandora/tools/westvault'] = array(
    'title' => 'Islandora WestVault Preservation',
    'description' => 'Configure the Islandora WestVault module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_westvault_admin'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/admin.form.inc',
    'access arguments' => array('ISLANDORA_WESTVAULT_ADMIN'),
  );
  $items['admin/islandora/tools/westvault/objects'] = array(
    'title' => 'Preserved objects list',
    'description' => 'See all preserved objects',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_westvault_show'),
    'type' => MENU_LOCAL_TASK,
    'access arguments' => array('ISLANDORA_WESTVAULT_ADMIN'),
  );
  return $items;
}

/**
 * Implements hook_cron().
 *
 * Detect objects with a PRESERVATION flag and preserve them. Skip objects already preserved.
 *
 */
function islandora_westvault_cron() {
  // Goal: Detect objects with the preservation flag and preserve them. Skip objects already preserved.
  module_load_include('inc', 'islandora_westvault', 'includes/utilities');
  // Prepare list of PIDs with PRESERVATION datastream
  $timestamp = time();
  // Run the thing, then set the last-update variable.
  $object_list = islandora_westvault_get_preservation_targets();  

  // Eliminate already-preserved objects from list
  $filtered_list = array();
  foreach ($object_list AS $object) {
    $object_test = islandora_object_load($object);
    // Read the XML from the existing datastream, and look for an "already preserved" tag.
    $ds = $object_test["PRESERVATION"];
    $xml = simplexml_load_string($ds->content);
    if (!isset($xml->confirmPreserved)) {    
      $filtered_list[] = $object;
    }
  }
  global $base_url;
  $sitename = parse_url($base_url);
  $pid_location = '/tmp/' . $sitename['host'] . '/';
  if (!is_dir($pid_location)) {
    mkdir($pid_location);
  }
  // Clear out the previous list of PIDs. Note that we probably don't need this list.
  // Use bag-it
  module_load_include('module', 'islandora_bagit');
  file_put_contents($pid_location . 'object_list.txt', '');

  foreach ($filtered_list AS $object) {
    $object_get = islandora_object_load($object);
    file_put_contents($pid_location . 'object_list.txt', $object . PHP_EOL, FILE_APPEND);
    islandora_bagit_create_bag($object_get);

    // Update the PRESERVATION datastream to timestamp successful preservation
    $ds = $object_get["PRESERVATION"];
    $ds_content = $ds->content;
    $dom = new DOMDocument();
    $dom->preserveWhiteSpace = FALSE;
    $dom->formatOutput = TRUE;
    $dom->loadXML($ds_content);
    
    $fragment = "<confirmPreserved>" . $timestamp . "</confirmPreserved>";
    $frag = $dom->createDocumentFragment();
    $frag->appendXML($fragment);
    $dom->documentElement->appendChild($frag);
    $ds_content_updated = $dom->saveXML($dom->documentElement);
    $ds->setContentFromString($ds_content_updated);
  }
  islandora_westvault_owncloud_sync();
}

/* 
 * Implements hook_islandora_object_ingested().
 */
function islandora_westvault_islandora_object_ingested(AbstractObject $object) {
  module_load_include('module', 'islandora_basic_collection');
  $parent_collections = islandora_get_parents_from_rels_ext($object);
  dd($parent_collections);
  foreach ($parent_collections AS $parent) {
    $parent_test = islandora_object_load($parent);
    $ds = $parent_test["PRESERVATION"];
    if (!empty($ds)) {
      $parent_preservation = TRUE;
    }
  }
  if ($parent_preservation == TRUE) {
    module_load_include('inc', 'islandora_westvault', 'includes/management_form');
    islandora_westvault_add_preservation_datastream($object);
  }
// For later    $xml = simplexml_load_string($ds->content);
}
